name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: docker
    steps:
      - name: Install uv
        uses: https://github.com/astral-sh/setup-uv@v5
        with:
          version: "0.5.11"

      - uses: actions/checkout@v4

      - name: Run CI script
        run: ./scripts/ci.sh
