name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.9.21"
      - uses: extractions/setup-just@v2
        with:
          version: "1.45.0"
      - name: Run tests
        run: just test

  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.9.21"
      - uses: extractions/setup-just@v2
        with:
          version: "1.45.0"
      - name: Run lint
        run: just lint
