name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install just
        run: apt-get update && apt-get install -y just
      - name: Run tests
        run: just test

  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install just
        run: apt-get update && apt-get install -y just
      - name: Run lint
        run: just lint
