name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.9.21/install.sh | sh
      - name: Install just
        run: |
          apt-get update && apt-get install -y wget
          wget -qO - https://just.systems/install.sh | bash -s -- --dest /usr/local/bin --tag 1.45.0
      - name: Run tests
        run: /usr/local/bin/just test

  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.9.21/install.sh | sh
      - name: Install just
        run: |
          apt-get update && apt-get install -y wget
          wget -qO - https://just.systems/install.sh | bash -s -- --dest /usr/local/bin --tag 1.45.0
      - name: Run lint
        run: /usr/local/bin/just lint
