name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: docker
    steps:
      - name: Install uv
        uses: https://github.com/astral-sh/setup-uv
      - uses: actions/checkout@v4
      - name: Run CI
        run: make ci
