name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: docker
    steps:
      - name: Install uv
        uses: https://github.com/astral-sh/setup-uv@v3

      - name: Install just
        uses: https://github.com/extractions/setup-just@v2

      - uses: actions/checkout@v4

      - name: Run ci
        run: just ci
