"""initial manager schema

Revision ID: 534287abf7fd
Revises:
Create Date: 2026-07-02 22:38:58.621369

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "534287abf7fd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    _create_sessions_table()
    _create_session_messages_table()
    _create_session_attachments_table()


def _create_sessions_table() -> None:
    if not _has_table("sessions"):
        op.create_table(
            "sessions",
            sa.Column("session_id", sa.String(), nullable=False),
            sa.Column("scope_id", sa.String(), nullable=False),
            sa.Column("title", sa.String(), nullable=True),
            sa.Column("version", sa.Integer(), server_default=sa.text("0"), nullable=False),
            sa.Column("created_at", sa.String(), nullable=False),
            sa.Column("updated_at", sa.String(), nullable=False),
            sa.Column("metadata_json", sa.String(), server_default=sa.text("'{}'"), nullable=False),
            sa.Column("worker_env_json", sa.String(), server_default=sa.text("'{}'"), nullable=False),
            sa.PrimaryKeyConstraint("session_id"),
        )
    else:
        columns = _column_names("sessions")
        if "worker_env_json" not in columns:
            op.add_column(
                "sessions",
                sa.Column("worker_env_json", sa.String(), server_default=sa.text("'{}'"), nullable=False),
            )
    _create_index("idx_sessions_scope_updated", "sessions", ("scope_id", "updated_at"))


def _create_session_messages_table() -> None:
    if not _has_table("session_messages"):
        op.create_table(
            "session_messages",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("session_id", sa.String(), nullable=False),
            sa.Column("version", sa.Integer(), nullable=False),
            sa.Column("role", sa.String(), nullable=False),
            sa.Column("payload_json", sa.String(), nullable=False),
            sa.Column("created_at", sa.String(), nullable=False),
            sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
    _create_index("idx_session_messages_session", "session_messages", ("session_id", "id"))


def _create_session_attachments_table() -> None:
    if not _has_table("session_attachments"):
        op.create_table(
            "session_attachments",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("attachment_id", sa.String(), nullable=False),
            sa.Column("session_id", sa.String(), nullable=False),
            sa.Column("message_id", sa.Integer(), nullable=False),
            sa.Column("sequence", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(), nullable=False),
            sa.Column("mime_type", sa.String(), nullable=False),
            sa.Column("size", sa.Integer(), nullable=False),
            sa.Column("path", sa.String(), nullable=False),
            sa.Column("sha256", sa.String(), nullable=False),
            sa.Column("created_at", sa.String(), nullable=False),
            sa.ForeignKeyConstraint(["message_id"], ["session_messages.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("session_id", "attachment_id"),
            sa.UniqueConstraint("session_id", "sequence"),
        )
    _create_index("idx_session_attachments_id", "session_attachments", ("session_id", "attachment_id"))
    _create_index("idx_session_attachments_message", "session_attachments", ("session_id", "message_id"))
    _create_index("idx_session_attachments_session", "session_attachments", ("session_id", "sequence"))
    _create_index(
        "idx_session_attachments_unique_id",
        "session_attachments",
        ("session_id", "attachment_id"),
        unique=True,
    )


def _has_table(table_name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(table_name)


def _column_names(table_name: str) -> set[str]:
    return {str(column["name"]) for column in sa.inspect(op.get_bind()).get_columns(table_name)}


def _index_names(table_name: str) -> set[str]:
    return {str(index["name"]) for index in sa.inspect(op.get_bind()).get_indexes(table_name)}


def _create_index(name: str, table_name: str, columns: tuple[str, ...], *, unique: bool = False) -> None:
    if name not in _index_names(table_name):
        op.create_index(name, table_name, list(columns), unique=unique)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_attachments", schema=None) as batch_op:
        batch_op.drop_index("idx_session_attachments_unique_id")
        batch_op.drop_index("idx_session_attachments_session")
        batch_op.drop_index("idx_session_attachments_message")
        batch_op.drop_index("idx_session_attachments_id")

    op.drop_table("session_attachments")
    with op.batch_alter_table("session_messages", schema=None) as batch_op:
        batch_op.drop_index("idx_session_messages_session")

    op.drop_table("session_messages")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("idx_sessions_scope_updated")

    op.drop_table("sessions")
    # ### end Alembic commands ###
