"""persist active session messages

Revision ID: 9f42afb992ec
Revises: 534287abf7fd
Create Date: 2026-07-24 12:22:07.668341

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "9f42afb992ec"
down_revision: str | None = "534287abf7fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stream_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("run_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("complete", sa.Boolean(), server_default=sa.text("1"), nullable=False))
        batch_op.create_index("idx_session_messages_run", ["session_id", "run_id"], unique=False)
        batch_op.create_unique_constraint("uq_session_messages_stream_id", ["session_id", "stream_id"])
        batch_op.drop_column("version")

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_column("version")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.INTEGER(), server_default=sa.text("0"), nullable=False))

    with op.batch_alter_table("session_messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.INTEGER(), server_default=sa.text("0"), nullable=False))
        batch_op.drop_constraint("uq_session_messages_stream_id", type_="unique")
        batch_op.drop_index("idx_session_messages_run")
        batch_op.drop_column("complete")
        batch_op.drop_column("run_id")
        batch_op.drop_column("stream_id")

    # ### end Alembic commands ###
