"""remove session versions

Revision ID: 9f42afb992ec
Revises: 534287abf7fd
Create Date: 2026-07-24 12:22:07.668341

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "9f42afb992ec"
down_revision: str | None = "534287abf7fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_messages", schema=None) as batch_op:
        batch_op.drop_column("version")

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_column("version")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.INTEGER(), server_default=sa.text("0"), nullable=False))

    with op.batch_alter_table("session_messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.INTEGER(), server_default=sa.text("0"), nullable=False))

    # ### end Alembic commands ###
